@startuml

|#39A2AE|Product Owner|
start
:stellt Agenda vor;
:stellt Sprintziel vor;

|#87B37A|Scrum Team|
:reflektiert Ergebnisse des vorherigen Sprints;
:ermittelt neue Kapazität;

|Product Owner|
:gibt Überblick über die Anforderungen;

|Scrum Team|
repeat
skinparam defaultTextAlignment left
rectangle #B8D5B8 (bespricht Anforderungen nacheinander) {
  :analysiert Anforderung;
  :bespricht Rahmenbedingungen und Einflussfaktoren;
  :Planning Poker;
  if (Aufnhame in das selektierte Produkt Backlog) then (nein)
    :legt Anforderung mit der neuen Schätzung inn das Produkt Backlog;
    :passt Ziel an;
  else (ja)
  endif
}
repeat while (mehr Anforderungen) is (ja) not (nein)

|#89608E|Scrum Master|
:dokumentiert Ergebnisse;
stop

@enduml
